name: tests unitaires
on: [push]
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - name: Set up Python for Demo
           uses: actions/setup-python@v4
         - name: installation de pytest
           run: pip3 install pytest
         - name: Run tests
           run: pytest TP1/test.py
         - name: Type OS executée
           run: echo "Type OS ${{ runner.os }}"
         - name: Version OS executée
           run: echo ("Version OS ", lsb_release -a)
         - name: localisation branche
           run: echo "Nom branche ${{ github.ref }}"
         - name: localisation répertoire
           run: echo "Nom repo ${{ github.repository }}"
         - name: verification version python
           run: echo ("version python ", python --version)
